#!/bin/bash

# Initializes the server. This serves as a proxy
# so as to allow for easier edits/fixes. This
# script in particular is utilized by that
# `minecraft.service` file which is symlinked
# to systemd services directory.

USR_ROOT=/home/minecraftd
APP_ROOT=$USR_ROOT/server/test
BIN_ROOT=$USR_ROOT/server/bin

export MCSERVER_RAM_INI=2048M
export MCSERVER_RAM_MAX=4096M

cd $APP_ROOT && $BIN_ROOT/mcserver spigot-1.19.2
